[package]
name = "schema_sync_macros"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Procedural macros for SchemaSync"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/schema_sync"
keywords = ["database", "orm", "schema", "migrations", "macros"]
categories = ["database"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
once_cell = "1.19"